benchmarker:
  video_path: "assets/new_track/driver_4.MOV"
  detection_model:
    model_path: "weights/best.pt"
    conf_threshold: 0.85
    shift_ratio: 0.02
  track_image_path: "assets/new_track/track-v2.jpg"
  reference_track_npy_path: "keypoints/new_track/all_path.npy"

  path_similarity:
    method: 'dtw' # dtw, frechet

    # one of these blocks (if `auto_tune` is True, the other block is ignored)
    auto_tune: True
    clamp_percentage: 0.05
    # or
    clamp_distance: 300.0
    distance_baseline: 3500.0

  time:
    distance_threshold_in_pixels: 50.0
    skip_first_x_seconds: 5.0


view_transformer:
  source_path: "keypoints/new_track/keypoints_from_camera.npy"
  target_path: "keypoints/new_track/keypoints_from_diagram.npy"


keypoints_definer:
  source_path: "assets/new_track/base.jpg"
  output_name: "test" # without .npy
  frame_number: 1 # if source is video
  override_if_exists: False


track_processor:
  image_path: "assets/new_track/track-v2.jpg"
  color_hsv: (330, 23, 84) # use https://pinetools.com/image-color-picker
  output_image_path_export: "assets/new_track/annotated_track.jpg"
  output_npy_path_export: "keypoints/new_track/all_track.npy"
  only_offset_the_outer: False
  dbscan:
    eps: 5.0
    min_samples: 5
    cluster_size_threshold: 30


actions:
  early_stop_after_x_seconds: # leave empty to disable
  show_live: True
  save_live_to_disk: True
